### ISSUE TITLE
The checklist

### ISSUE THREAD

**Issue by shahriarshafin** [shahriarshafin/shahriarshafin.github.io#27]
- [ ] link to p tag

- [ ] use a tag instead in link

- [ ] when scroll the  vector head up

- [ ] rename tailwind custom class

        'sh-white': '#EDEDEE',
        'sh-white-500': '#929A9E',
        'sh-blue': '#1A85FF',
        'sh-blue-500': '#8AC5EB',
        'sh-purple': '#ec4899',
        'sh-dark': '#2D3748',
        'sh-dark-500': '#1A202C'

- [ ] separate the meta

- [ ] google-site-verification: google489e3b0296208014.html

- [ ] image compress

- [ ] use direct svg not react icons

- [ ] add ts
